// Code generated by hertz generator.

package handler

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _fileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadfileMw() []app.HandlerFunc {
	// your code...
	return nil
}
