syntax = "proto3";

package onij;

option go_package = "api";

import "api.proto";
import "all_enum.proto";
import "all_model.proto";

// 上传文件
message UploadFileReq {
  message FileInfo {
    string filename = 1;
    string file = 2;
    int64 origin_at = 3;
  }
  int64 parent_id = 1;         // 父级文件夹id
  repeated FileInfo files = 2; // 文件列表
}
message UploadFileResp {
  int32 code = 1;
  string message = 2;
  repeated int64 file_ids = 3;
}

// 上传音乐
message UploadMusicReq {
  // 基础信息
  string name = 1;
  repeated int64 artist_ids = 2;
  int64 mp3_file_id = 3;
  int64 lyrics_file_id = 4;

  // 表单信息
  optional int64 composer_id = 10;
  optional int64 writer_id = 11;
  optional int64 album_id = 12;
  optional string mv_url = 13;
  optional int64 root_music_id = 14;
  optional int32 issue_time = 15;

  // update
  optional int64 music_id = 50;
}
message UploadMusicResp {
  int32 code = 1;
  string message = 2;
  int64 music_id = 3;
}

message UploadArtistReq {
  string name = 1;
  ArtistType artist_type = 2;
}
message UploadArtistResp {
  int32 code = 1;
  string message = 2;
  int64 artist_id = 3;
}

message UploadTagReq { TagDetail tag_detail = 1; }
message UploadTagResp {
  int32 code = 1;
  string message = 2;
}

// 上传专辑
message UploadAlbumReq {
  string name = 1;
  int64 artist_id = 2;
  int64 cover_file_id = 3;
  int32 issue_time = 4;
  optional int64 music_id = 5;
  optional int64 related_album_id = 6;
}
message UploadAlbumResp {
  int32 code = 1;
  string message = 2;
  int64 album_id = 3;
}

// 获取音乐详情
message GetMusicDetailReq { int64 music_id = 1; }
message GetMusicDetailResp {
  int32 code = 1;
  string message = 2;
  MusicDetail detail = 3;
}

// 获取专辑详情
message GetAlbumDetailReq { int64 album_id = 1; }
message GetAlbumDetailResp {
  int32 code = 1;
  string message = 2;
  AlbumDetail detail = 3;
}

// 获取音乐列表
message GetMusicListReq {
  MusicSortType sort_type = 1;
  repeated string keywords = 2;
  optional int64 album_id = 3;
  repeated int64 artist_ids = 4;
  repeated int64 writer_ids = 5;
  repeated int64 composer_ids = 6;
  repeated TagType tag_types = 7;

  int32 page = 10;
  int32 limit = 11;
}
message GetMusicListResp {
  int32 code = 1;
  string message = 2;

  repeated MusicProfile musics = 10;
}

// 获取文件列表
message GetFileListReq {
  int64 parent_id = 1;
  int32 page = 10;
  int32 limit = 11;
}
message GetFileListResp {
  int32 code = 1;
  string message = 2;
  repeated FileDetail files = 10;
  int32 total = 11;
}

// 下载文件
message DownloadFileReq { repeated int64 file_ids = 1; }
message DownloadFileResp {
  int32 code = 1;
  string message = 2;
  repeated string urls = 10;
}

message SearchArtistReq {
  string keyword = 1;
  optional TagGroup tag_group = 2;
  optional TagType tag_type = 3;
  int32 page = 10;
  int32 limit = 11;
}
message SearchArtistResp {
  int32 code = 1;
  string message = 2;

  repeated ArtistProfile artists = 10;
}

message DeleteTagReq {
  int64 resource_id = 1;
  TagType tag_type = 2;
}
message DeleteTagResp {
  int32 code = 1;
  string message = 2;
}

message DeleteFileReq { int64 file_id = 1; }
message DeleteFileResp {
  int32 code = 1;
  string message = 2;
}

service AllService {
  // 上传文件
  rpc UploadFile(UploadFileReq) returns (UploadFileResp) {
    option (api.post) = "/file/upload";
  }
  // 上传音乐
  rpc UploadMusic(UploadMusicReq) returns (UploadMusicResp) {
    option (api.post) = "/music/upload";
  }
  // 上传专辑
  rpc UploadAlbum(UploadAlbumReq) returns (UploadAlbumResp) {
    option (api.post) = "/album/upload";
  }
  // 上传艺术家
  rpc UploadArtist(UploadArtistReq) returns (UploadArtistResp) {
    option (api.post) = "/artist/upload";
  }
  // 上传标签
  rpc UploadTag(UploadTagReq) returns (UploadTagResp) {
    option (api.post) = "/tag/upload";
  }
  // 获取音乐详情
  rpc GetMusicDetail(GetMusicDetailReq) returns (GetMusicDetailResp) {
    option (api.post) = "/music/detail";
  }
  // 获取专辑详情
  rpc GetAlbumDetail(GetAlbumDetailReq) returns (GetAlbumDetailResp) {
    option (api.post) = "/album/detail";
  }
  // 获取音乐列表
  rpc GetMusicList(GetMusicListReq) returns (GetMusicListResp) {
    option (api.post) = "/music/list";
  }
  // 获取文件列表
  rpc GetFileList(GetFileListReq) returns (GetFileListResp) {
    option (api.post) = "/file/list";
  }
  // 下载文件
  rpc DownloadFile(DownloadFileReq) returns (DownloadFileResp) {
    option (api.post) = "/file/download";
  }
  // 搜索艺术家
  rpc SearchArtist(SearchArtistReq) returns (SearchArtistResp) {
    option (api.post) = "/artist/search";
  }
  // 删除标签
  rpc DeleteTag(DeleteTagReq) returns (DeleteTagResp) {
    option (api.post) = "/tag/delete";
  }
  // 删除文件
  rpc DeleteFile(DeleteFileReq) returns (DeleteFileResp) {
    option (api.post) = "/file/delete";
  }
}
