syntax = "proto3";

package onij;

option go_package = "api";

import "api.proto";
import "all_enum.proto";
import "all_model.proto";

// 上传文件
message UploadFileReq {
  message FileInfo {
    string filename = 1;  // 文件名
    string store_key = 2; // 七牛存储key
    string hash = 3;      // 文件hash值
    FileType format = 4;  // 文件类型
    string exif = 5;      // 扩展
    int64 size = 6;       // 文件大小
  }
  int64 parent_id = 1;         // 父级文件夹id
  repeated FileInfo files = 2; // 文件列表
}
message UploadFileResp {
  int32 code = 1;
  string message = 2;
  repeated int64 file_ids = 3;
}

// 上传音乐
message UploadMusicReq {
  // 基础信息
  string name = 1;
  string sub_name = 2;
  repeated int64 artist_ids = 3;
  int64 audio_file_id = 4;
  int64 lyric_file_id = 5;
  int32 time_length = 6;

  // 表单信息
  repeated int64 composer_ids = 10;
  repeated int64 writer_ids = 11;
  optional int64 album_id = 12;
  optional string mv_url = 13;
  optional int64 root_music_id = 14;
  optional int32 issue_time = 15;
  optional int32 priority = 16;
  optional string lyric_content = 17;
  AudioQuality audio_quality = 18;
  PerformType perform_type = 19;

  // update
  optional int64 music_id = 50;
}
message UploadMusicResp {
  int32 code = 1;
  string message = 2;
  int64 music_id = 3;
}

message UploadArtistReq {
  string name = 1;
  optional int64 avatar_file_id = 2;

  optional string artist_id = 10;
}
message UploadArtistResp {
  int32 code = 1;
  string message = 2;
  int64 artist_id = 3;
}

message UploadTagReq { Tag tag = 1; }
message UploadTagResp {
  int32 code = 1;
  string message = 2;
}

// 上传专辑
message UploadAlbumReq {
  message AlbumMusic {
    string name = 1;
    int32 time_length = 2;
    int64 music_id = 3;
    bool is_available = 4;
  }
  string name = 1;
  string profile = 2;
  repeated int64 artist_ids = 3;
  int64 cover_file_id = 4;
  int32 issue_time = 5;
  AlbumType album_type = 6;
  string live_url = 7;
  repeated AlbumMusic album_musics = 8;

  optional int64 album_id = 10;
}
message UploadAlbumResp {
  int32 code = 1;
  string message = 2;
  int64 album_id = 3;
}

// 获取音乐详情
message GetMusicDetailReq { int64 music_id = 1; }
message GetMusicDetailResp {
  int32 code = 1;
  string message = 2;
  Music music = 3;
}

// 获取专辑详情
message GetAlbumDetailReq { int64 album_id = 1; }
message GetAlbumDetailResp {
  int32 code = 1;
  string message = 2;
  Album album = 3;
  repeated AlbumMusic album_musics = 4;
}

// 获取音乐列表
message GetMusicListReq {
  string keyword = 1;
  repeated int64 artist_ids = 2;
  repeated TagType tag_types = 3;

  int32 page = 10;
  int32 limit = 11;
}
message GetMusicListResp {
  int32 code = 1;
  string message = 2;
  repeated Music musics = 10;
}

// 获取文件列表
message GetFileListReq {
  optional int64 parent_id = 1;
  string keyword = 2;
  int32 page = 10;
  int32 limit = 11;
}
message GetFileListResp {
  int32 code = 1;
  string message = 2;
  repeated File files = 10;
  int32 total = 11;
}

message GetArtistDetailReq {
  string keyword = 1;
  optional TagGroup tag_group = 2;
  optional TagType tag_type = 3;
  int32 page = 10;
  int32 limit = 11;
}
message GetArtistDetailResp {
  int32 code = 1;
  string message = 2;

  repeated Artist artists = 10;
}

message GetAlbumListReq {
  string keyword = 1;
  optional int64 artist_id = 2;
  int32 page = 10;
  int32 limit = 11;
}
message GetAlbumListResp {
  int32 code = 1;
  string message = 2;
  repeated Album albums = 10;
}

message DeleteFileReq { int64 file_id = 1; }
message DeleteFileResp {
  int32 code = 1;
  string message = 2;
}

message DeleteTagReq {
  int64 resource_id = 1;
  TagType tag_type = 2;
}
message DeleteTagResp {
  int32 code = 1;
  string message = 2;
}

// 获取上传token
message GetUploadTokenReq {}
message GetUploadTokenResp {
  int32 code = 1;
  string message = 2;
  string upload_token = 3;
  string domain = 4;
}

service AllService {
  // 上传文件
  rpc UploadFile(UploadFileReq) returns (UploadFileResp) {
    option (api.post) = "/file/upload";
  }
  // 上传音乐
  rpc UploadMusic(UploadMusicReq) returns (UploadMusicResp) {
    option (api.post) = "/music/upload";
  }
  // 上传专辑
  rpc UploadAlbum(UploadAlbumReq) returns (UploadAlbumResp) {
    option (api.post) = "/album/upload";
  }
  // 上传艺术家
  rpc UploadArtist(UploadArtistReq) returns (UploadArtistResp) {
    option (api.post) = "/artist/upload";
  }
  // 上传标签
  rpc UploadTag(UploadTagReq) returns (UploadTagResp) {
    option (api.post) = "/tag/upload";
  }
  // 获取音乐详情
  rpc GetMusicDetail(GetMusicDetailReq) returns (GetMusicDetailResp) {
    option (api.post) = "/music/detail";
  }
  // 获取专辑详情
  rpc GetAlbumDetail(GetAlbumDetailReq) returns (GetAlbumDetailResp) {
    option (api.post) = "/album/detail";
  }
  // 获取音乐列表
  rpc GetMusicList(GetMusicListReq) returns (GetMusicListResp) {
    option (api.post) = "/music/list";
  }
  // 获取文件列表
  rpc GetFileList(GetFileListReq) returns (GetFileListResp) {
    option (api.post) = "/file/list";
  }
  // 删除文件
  rpc DeleteFile(DeleteFileReq) returns (DeleteFileResp) {
    option (api.post) = "/file/delete";
  }
  // 删除标签
  rpc DeleteTag(DeleteTagReq) returns (DeleteTagResp) {
    option (api.post) = "/tag/delete";
  }
  // 获取上传token
  rpc GetUploadToken(GetUploadTokenReq) returns (GetUploadTokenResp) {
    option (api.post) = "/file/upload_token";
  }
}
