syntax = "proto3";

package onij;

option go_package = "api";

import "api.proto";
import "all_enum.proto";

message MusicDetail {
  int64 id = 1;
  string name = 2;
  repeated int64 artist_ids = 3;
  repeated string artist_names = 4;
  int64 composer_id = 5;
  string composer_name = 6;
  int64 writer_id = 7;
  string writer_name = 8;
  int32 issue_time = 9;
  string mv_url = 10;

  string mp3_file_url = 21;
  string lyrics_file_url = 22;

  // 专辑信息
  AlbumProfile album_profile = 30;
  // 标签信息
  repeated TagDetail tag_details = 31;
}

message TagDetail {
  int64 resource_id = 1;
  int32 resource_type = 2;
  TagBiz tag_biz = 3;
  TagGroup tag_group = 4;
  TagType tag_type = 5;
  optional int64 target_id = 6;
  optional int32 target_type = 7;
  string extra = 8;
  bool list_show = 9;
}

message AlbumDetail {
  int64 id = 1;
  string name = 2;
  int64 artist_id = 3;
  string artist_name = 4;
  int32 issue_time = 5;

  string cover_file_url = 20;
  string mv_url = 21;

  repeated MusicProfile related_musics = 30;
}

message AlbumProfile {
  int64 id = 1;
  string name = 2;
  string cover_file_url = 3;
}

message MusicProfile {
  int64 id = 1;
  string name = 2;
  repeated ArtistProfile singer_profiles = 3;
  repeated TagDetail tags = 4;
}

message ArtistProfile {
  int64 id = 1;
  string name = 2;
  ArtistType artist_type = 3;
}