syntax = "proto3";

package onij;

option go_package = "api";

import "api.proto";

enum FileType {
  FT_Unknown = 0;
  FT_Mp3 = 1;
  FT_Lyrics = 2;
  FT_Png = 3;
  FT_Folder = 99;
}

enum ArtistType {
  AT_Unknown = 0;
  AT_Singer = 1;
  AT_Writer = 2;
  AT_Composer = 3;
}

enum MusicSortType {
  MST_Unknown = 0;
  MST_Created_At_Desc = 1;
  MST_Created_At_Asc = 2;
  MST_Issue_Time_Desc = 3;
  MST_Issue_Time_Asc = 4;
}

enum TagBiz {
  TB_Unknown = 0;
  TB_Music = 1;
}

enum TagGroup {
  TG_Unknown = 0;
  TG_MusicTheme = 101;
  TG_MusicStyle = 102;
  TG_MusicEmotion = 103;
  TG_MusicHighlight = 104;
  TG_MusicCollection = 105;

  TG_ArtistStar = 120;
}

enum TagType {
  TT_Unknown = 0;
  // 10101

  // 10201

  // 10301

  // 10401
  TT_NcBridge = 10401;

  // 10501

  // 12001
  TT_Star = 12001;
}

enum ResourceType {
  RT_Unknown = 0;
  RT_Artist = 1;
  RT_Music = 2;
  RT_Album = 3;
}