syntax = "proto3";

package onij;

option go_package = "api";

import "api.proto";
import "all_enum.proto";

message Music {
  int64 id = 1;
  string name = 2;
  repeated Artist artists = 3;
  repeated Artist composers = 4;
  repeated Artist writers = 5;
  int32 issue_time = 6;
  string mv_url = 7;
  string audio_file_url = 8;
  string lyrics_file_url = 9;
  repeated Album album = 10;
  repeated Tag tags = 11;
}

message Tag {
  int64 id = 1;
  int64 resource_id = 2;
  ResourceType resource_type = 3;
  TagBiz tag_biz = 4;
  TagGroup tag_group = 5;
  TagType tag_type = 6;
  int64 target_id = 7;
  string extra = 9;
}

message Artist {
  int64 id = 1;
  string name = 2;
  string avatar_file_url = 3;
  repeated ArtistType artist_types = 4;
}

message Album {
  int64 id = 1;
  string name = 2;
  string profile = 3;
  AlbumType album_type = 4;
  repeated Artist artists = 5;
  int32 issue_time = 6;
  string cover_file_url = 7;
  string live_url = 8;

  repeated AlbumMusic album_musics = 20;
}

message AlbumMusic {
  string name = 1;
  int32 time_length = 2;
  int64 music_id = 3;
  repeated Artist artists = 4;
  bool is_available = 5;
}

message File {
  int64 id = 1;
  string name = 2;
  FileType format = 3;
  int32 size = 4;
  int64 parent_id = 5;
  string extra = 6;
  int64 created_at = 7;
  int64 updated_at = 8;
  string url = 10;
}
