syntax = "proto3";

package onij;

option go_package = "api";

import "api.proto";

message MusicDetail {
  int64 id = 1;
  string name = 2;
  repeated int64 artist_ids = 3;
  repeated string artist_names = 4;
  string composer_id = 5;
  string composer_name = 6;
  string writer_id = 7;
  string writer_name = 8;
  int64 issue_time = 9;
  string mv_url = 10;

  string mp3_file_url = 21;
  string lyrics_file_url = 22;

  int64 album_id = 30;
  string album_name = 31;
}

message AlbumDetail {
  message RelatedMusic {
    int64 id = 1;
    string name = 2;
  }
  int64 id = 1;
  string name = 2;
  int64 artist_id = 3;
  string artist_name = 4;
  int64 issue_time = 5;

  string cover_file_url = 20;
  string mv_file_url = 21;

  repeated RelatedMusic related_musics = 30;
}