syntax = "proto3";

package onij;

option go_package = "api";

enum FileType {
  FT_Unknown = 0;
  FT_Pdf = 1;
  FT_Word = 2;
  FT_Excel = 3;
  FT_PowerPoint = 4;
  FT_Image = 5;
  FT_Video = 6;
  FT_Audio = 7;
  FT_Text = 8;
  FT_Archive = 9;
  FT_Code = 10;
  FT_CSV = 11;
  FT_Executable = 12;
  FT_Folder = 99;
}

enum ArtistType {
  ATT_Unknown = 0;
  ATT_Artist = 1;
  ATT_Writer = 2;
  ATT_Composer = 3;
}

// 专辑类型
enum AlbumType {
  ALT_Unknown = 0;
  ALT_Studio = 1; // 录音室专辑
  ALT_Live = 2;   // 现场专辑
  ALT_OST = 3;    // 原声带专辑
  ALT_Cover = 4;  // 翻唱专辑
  ALT_Other = 99;
}

enum AudioQuality {
  AQ_Unknown = 0;
  AQ_Low = 1;
}

enum PerformType {
  PT_Unknown = 0;
}

// 标签业务
enum TagBiz {
  TB_Unknown = 0;
  TB_Music = 1;
}

// 标签组
enum TagGroup {
  TG_Unknown = 0;
  TG_MusicTheme = 101;
  TG_MusicStyle = 102;
  TG_MusicEmotion = 103;
  TG_MusicHighlight = 104;
  TG_MusicCollection = 105;

  TG_ArtistStar = 120;
}

// 标签类型
enum TagType {
  TT_Unknown = 0;
  // 10101

  // 10201

  // 10301

  // 10401
  TT_NcBridge = 10401;

  // 10501

  // 12001
  TT_Star = 12001;
}

// 资源类型
enum ResourceType {
  RT_Unknown = 0;
  RT_Artist = 1;
  RT_Music = 2;
  RT_Album = 3;
}
