// Code generated by hertz generator.

package api

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _albumMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getalbumdetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadalbumMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _fileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadfileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _musicMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getmusicdetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadmusicMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _artistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadartistMw() []app.HandlerFunc {
	// your code...
	return nil
}
