// Code generated by hertz generator.

package main

import (
	handler "onij/handler"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// 添加获取上传token的路由
	r.POST("/file/upload_token", handler.GetUploadToken)

	// your code ...
}
