// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v5.28.3
// source: all_enum.proto

package handler

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "onij/model/api"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppId int32

const (
	AppId_AppId_Unknown AppId = 0
	AppId_AppId_Music   AppId = 1
)

// Enum value maps for AppId.
var (
	AppId_name = map[int32]string{
		0: "AppId_Unknown",
		1: "AppId_Music",
	}
	AppId_value = map[string]int32{
		"AppId_Unknown": 0,
		"AppId_Music":   1,
	}
)

func (x AppId) Enum() *AppId {
	p := new(AppId)
	*p = x
	return p
}

func (x AppId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AppId) Descriptor() protoreflect.EnumDescriptor {
	return file_all_enum_proto_enumTypes[0].Descriptor()
}

func (AppId) Type() protoreflect.EnumType {
	return &file_all_enum_proto_enumTypes[0]
}

func (x AppId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AppId.Descriptor instead.
func (AppId) EnumDescriptor() ([]byte, []int) {
	return file_all_enum_proto_rawDescGZIP(), []int{0}
}

var File_all_enum_proto protoreflect.FileDescriptor

var file_all_enum_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x61, 0x6c, 0x6c, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x6f, 0x6e, 0x69, 0x6a, 0x1a, 0x09, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2a, 0x2b, 0x0a, 0x05, 0x41, 0x70, 0x70, 0x49, 0x64, 0x12, 0x11, 0x0a, 0x0d, 0x41, 0x70,
	0x70, 0x49, 0x64, 0x5f, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x0f, 0x0a,
	0x0b, 0x41, 0x70, 0x70, 0x49, 0x64, 0x5f, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x10, 0x01, 0x42, 0x14,
	0x5a, 0x12, 0x6f, 0x6e, 0x69, 0x6a, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x68, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_all_enum_proto_rawDescOnce sync.Once
	file_all_enum_proto_rawDescData = file_all_enum_proto_rawDesc
)

func file_all_enum_proto_rawDescGZIP() []byte {
	file_all_enum_proto_rawDescOnce.Do(func() {
		file_all_enum_proto_rawDescData = protoimpl.X.CompressGZIP(file_all_enum_proto_rawDescData)
	})
	return file_all_enum_proto_rawDescData
}

var file_all_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_all_enum_proto_goTypes = []interface{}{
	(AppId)(0), // 0: onij.AppId
}
var file_all_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_all_enum_proto_init() }
func file_all_enum_proto_init() {
	if File_all_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_all_enum_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_all_enum_proto_goTypes,
		DependencyIndexes: file_all_enum_proto_depIdxs,
		EnumInfos:         file_all_enum_proto_enumTypes,
	}.Build()
	File_all_enum_proto = out.File
	file_all_enum_proto_rawDesc = nil
	file_all_enum_proto_goTypes = nil
	file_all_enum_proto_depIdxs = nil
}
