// Code generated by hertz generator.

package handler

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"onij/biz/prm"
	api "onij/model/api"
)

// AiChat .
// @router /ai/chat [POST]
func AiChat(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.AiChatReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := ser.AiLogic.Chat(ctx, prm.NewAiChatParam(&req))
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	c.JSON(consts.StatusOK, resp)
}
