// Code generated by hertz generator.

package handler

import (
	"context"
	"onij/biz/errdef"

	"onij/biz/prm"
	api "onij/model/api"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// DeleteFile .
// @router /file/delete [POST]
func DeleteFile(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.DeleteFileReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	if err = checkDeleteFileReq(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := ser.FileLogic.Delete(ctx, prm.NewDeleteFileParam(&req))
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}
	c.JSON(consts.StatusOK, resp.Resp())
}

func checkDeleteFileReq(req *api.DeleteFileReq) error {
	if req.FileId <= 0 {
		return errdef.ErrInvalidFileId
	}
	return nil
}
