// Code generated by hertz generator.

package handler

import (
	"context"

	"onij/biz/prm"
	api "onij/model/api"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// DeleteTag .
// @router /tag/delete [POST]
func DeleteTag(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.DeleteTagReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	if err = checkDeleteTagReq(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := ser.TagLogic.Delete(ctx, prm.NewDeleteTagParam(&req))
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}
	c.JSON(consts.StatusOK, resp.Resp())
}

func checkDeleteTagReq(req *api.DeleteTagReq) error {
	return nil
}
