// Code generated by hertz generator.

package handler

import (
	"context"

	"onij/biz/prm"
	api "onij/model/api"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// DownloadFile .
// @router /file/download [POST]
func DownloadFile(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.DownloadFileReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	if err = checkDownloadFileReq(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := ser.FileLogic.DownloadByIds(ctx, prm.NewDownloadFileParam(&req))
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}
	c.JSON(consts.StatusOK, resp.Resp())
}

func checkDownloadFileReq(req *api.DownloadFileReq) error {
	return nil
}
