// Code generated by hertz generator.

package handler

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	api "onij/model/api"
)

// GetMusicList .
// @router /music/list [GET]
func GetMusicList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.GetMusicListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.GetMusicListResp)

	c.JSON(consts.StatusOK, resp)
}
