// Code generated by hertz generator.

package handler

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	handler "onij/model/handler"
)

// GetAlbumDetail .
// @router /album/detail [GET]
func GetAlbumDetail(ctx context.Context, c *app.RequestContext) {
	var err error
	var req handler.GetAlbumDetailReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(handler.GetAlbumDetailResp)

	c.JSON(consts.StatusOK, resp)
}
