// Code generated by hertz generator.

package handler

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"onij/biz/prm"
	api "onij/model/api"
)

// GetMemoList .
// @router /memo/list [POST]
func GetMemoList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.GetMemoListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	if err = checkGetMemoListReq(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := ser.MemoLogic.GetList(ctx, prm.NewGetMemoListParam(&req))
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}
	c.JSON(consts.StatusOK, resp.Resp())
}

func checkGetMemoListReq(req *api.GetMemoListReq) error {
	return nil
}
