// Code generated by hertz generator.

package handler

import (
	"context"

	"onij/biz/prm"
	api "onij/model/api"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// GetFileList .
// @router /file/list [POST]
func GetFileList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.GetFileListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	if err = checkGetFileListReq(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := ser.FileLogic.GetList(ctx, prm.NewGetFileListParam(&req))
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}
	c.JSON(consts.StatusOK, resp.Resp())
}

func checkGetFileListReq(req *api.GetFileListReq) error {
	return nil
}
