// Code generated by hertz generator.

package handler

import (
	"context"
	"onij/util"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// GetUploadToken .
// @router /file/upload_token [POST]
func GetUploadToken(ctx context.Context, c *app.RequestContext) {
	resp := map[string]interface{}{
		"code":         util.BaseCodeOK,
		"message":      util.BaseMsgOK,
		"upload_token": util.GetUploadToken(),
		"domain":       util.PublicDomain(),
		"upload_url":   util.GetUploadURL(),
	}
	c.JSON(consts.StatusOK, resp)
}
