// Code generated by hertz generator.

package handler

import (
	"context"

	"onij/biz/prm"
	api "onij/model/api"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// GetMemoDetail .
// @router /memo/detail [POST]
func GetMemoDetail(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.GetMemoDetailReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	if err = checkGetMemoDetailReq(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := ser.MemoLogic.GetDetail(ctx, prm.NewGetMemoDetailParam(&req))
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}
	c.JSON(consts.StatusOK, resp.Resp())
}

func checkGetMemoDetailReq(req *api.GetMemoDetailReq) error {
	return nil
}
