// Code generated by hertz generator.

package handler

import (
	"context"
	"onij/biz/prm"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	api "onij/model/api"
)

// GetArtistList .
// @router /artist/list [POST]
func GetArtistList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.GetArtistListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	if err = checkGetArtistListReq(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := ser.ArtistLogic.GetList(ctx, prm.NewGetArtistListParam(&req))
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}
	c.JSON(consts.StatusOK, resp.Resp())
}

func checkGetArtistListReq(req *api.GetArtistListReq) error {
	return nil
}
