// Code generated by hertz generator.

package handler

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	api "onij/model/api"
)

// GetMusicDetail .
// @router /music/detail [GET]
func GetMusicDetail(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.GetMusicDetailReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	if err = checkGetMusicReq(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := ser.MusicLogic.GetDetail(ctx, prm.NewGetMusicParam(&req))
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}
	c.JSON(consts.StatusOK, resp.Resp())
}

func checkGetMusicReq(req *api.GetMusicDetailReq) error {
	return nil
}
