// Code generated by hertz generator.

package handler

import (
	"context"
	"onij/biz/prm"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	api "onij/model/api"
)

// GetAlbumDetail .
// @router /album/detail [GET]
func GetAlbumDetail(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.GetAlbumDetailReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	if err = checkGetAlbumReq(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := ser.AlbumLogic.GetDetail(ctx, prm.NewGetAlbumParam(&req))
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}
	c.JSON(consts.StatusOK, resp.Resp())
}

func checkGetAlbumReq(req *api.GetAlbumDetailReq) error {
	return nil
}
