// Code generated by hertz generator.

package handler

import (
	"context"

	"onij/biz/prm"
	api "onij/model/api"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// GetTagList .
// @router /tag/list [POST]
func GetTagList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.GetTagListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	if err = checkGetTagListReq(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := ser.TagLogic.GetList(ctx, prm.NewGetTagListParam(&req))
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}
	c.JSON(consts.StatusOK, resp.Resp())
}

func checkGetTagListReq(req *api.GetTagListReq) error {
	return nil
}
