// Code generated by hertz generator.

package handler

import (
	"context"
	"onij/biz/prm"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	api "onij/model/api"
)

// UploadMusic .
// @router /music/upload [POST]
func UploadMusic(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.UploadMusicReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	if err = checkUploadMusicReq(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := ser.MusicLogic.Upload(ctx, prm.NewUploadMusicParam(&req))
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	c.JSON(consts.StatusOK, resp)
}

func checkUploadMusicReq(req *api.UploadMusicReq) error {
	return nil
}
