// Code generated by hertz generator.

package handler

import (
	"context"
	"onij/biz/prm"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	api "onij/model/api"
)

// UploadArtist .
// @router /artist/upload [POST]
func UploadArtist(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.UploadArtistReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	if err = checkUploadArtistReq(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := ser.ArtistLogic.Upload(ctx, prm.NewUploadArtistParam(&req))
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}
	c.JSON(consts.StatusOK, resp.Resp())
}

func checkUploadArtistReq(req *api.UploadArtistReq) error {
	return nil
}
