// Code generated by hertz generator.

package handler

import (
	"context"
	"errors"

	"onij/biz/prm"
	api "onij/model/api"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// UploadTag .
// @router /tag/upload [POST]
func UploadTag(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.UploadTagReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	if err = checkUploadTagReq(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := ser.TagLogic.Upload(ctx, prm.NewUploadTagParam(&req))
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}
	c.JSON(consts.StatusOK, resp.Resp())
}

func checkUploadTagReq(req *api.UploadTagReq) error {
	if req.TagDetail == nil {
		return errors.New("tag detail is nil")
	}
	return nil
}
