// Code generated by hertz generator.

package handler

import (
	"context"
	"onij/biz/prm"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	api "onij/model/api"
)

// UploadAlbum .
// @router /album/upload [POST]
func UploadAlbum(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.UploadAlbumReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	if err = checkUploadAlbumReq(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := ser.AlbumLogic.Upload(ctx, prm.NewUploadAlbumParam(&req))
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}
	c.JSON(consts.StatusOK, resp)
}

func checkUploadAlbumReq(req *api.UploadAlbumReq) error {
	return nil
}
