// Code generated by hertz generator.

package handler

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"onij/biz/prm"
	api "onij/model/api"
)

// UploadMemo .
// @router /memo/upload [POST]
func UploadMemo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.UploadMemoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	if err = checkUploadMemoReq(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := ser.MemoLogic.Upload(ctx, prm.NewUploadMemoParam(&req))
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}
	c.JSON(consts.StatusOK, resp.Resp())
}

func checkUploadMemoReq(req *api.UploadMemoReq) error {
	return nil
}
