// Code generated by hertz generator.

package handler

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	handler "onij/model/handler"
)

// UploadAlbum .
// @router /album/upload [POST]
func UploadAlbum(ctx context.Context, c *app.RequestContext) {
	var err error
	var req handler.UploadAlbumReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(handler.UploadAlbumResp)

	c.JSON(consts.StatusOK, resp)
}
