// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v5.28.3
// source: all_enum.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppId int32

const (
	AppId_AppId_Unknown AppId = 0
	AppId_AppId_Music   AppId = 1
)

// Enum value maps for AppId.
var (
	AppId_name = map[int32]string{
		0: "AppId_Unknown",
		1: "AppId_Music",
	}
	AppId_value = map[string]int32{
		"AppId_Unknown": 0,
		"AppId_Music":   1,
	}
)

func (x AppId) Enum() *AppId {
	p := new(AppId)
	*p = x
	return p
}

func (x AppId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AppId) Descriptor() protoreflect.EnumDescriptor {
	return file_all_enum_proto_enumTypes[0].Descriptor()
}

func (AppId) Type() protoreflect.EnumType {
	return &file_all_enum_proto_enumTypes[0]
}

func (x AppId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AppId.Descriptor instead.
func (AppId) EnumDescriptor() ([]byte, []int) {
	return file_all_enum_proto_rawDescGZIP(), []int{0}
}

type FileType int32

const (
	FileType_FT_Unknown FileType = 0
	FileType_FT_Mp3     FileType = 1
	FileType_FT_Lyrics  FileType = 2
	FileType_FT_Png     FileType = 3
)

// Enum value maps for FileType.
var (
	FileType_name = map[int32]string{
		0: "FT_Unknown",
		1: "FT_Mp3",
		2: "FT_Lyrics",
		3: "FT_Png",
	}
	FileType_value = map[string]int32{
		"FT_Unknown": 0,
		"FT_Mp3":     1,
		"FT_Lyrics":  2,
		"FT_Png":     3,
	}
)

func (x FileType) Enum() *FileType {
	p := new(FileType)
	*p = x
	return p
}

func (x FileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileType) Descriptor() protoreflect.EnumDescriptor {
	return file_all_enum_proto_enumTypes[1].Descriptor()
}

func (FileType) Type() protoreflect.EnumType {
	return &file_all_enum_proto_enumTypes[1]
}

func (x FileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileType.Descriptor instead.
func (FileType) EnumDescriptor() ([]byte, []int) {
	return file_all_enum_proto_rawDescGZIP(), []int{1}
}

type ArtistType int32

const (
	ArtistType_AT_Unknown  ArtistType = 0
	ArtistType_AT_Singer   ArtistType = 1
	ArtistType_AT_Writer   ArtistType = 2
	ArtistType_AT_Composer ArtistType = 3
)

// Enum value maps for ArtistType.
var (
	ArtistType_name = map[int32]string{
		0: "AT_Unknown",
		1: "AT_Singer",
		2: "AT_Writer",
		3: "AT_Composer",
	}
	ArtistType_value = map[string]int32{
		"AT_Unknown":  0,
		"AT_Singer":   1,
		"AT_Writer":   2,
		"AT_Composer": 3,
	}
)

func (x ArtistType) Enum() *ArtistType {
	p := new(ArtistType)
	*p = x
	return p
}

func (x ArtistType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArtistType) Descriptor() protoreflect.EnumDescriptor {
	return file_all_enum_proto_enumTypes[2].Descriptor()
}

func (ArtistType) Type() protoreflect.EnumType {
	return &file_all_enum_proto_enumTypes[2]
}

func (x ArtistType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArtistType.Descriptor instead.
func (ArtistType) EnumDescriptor() ([]byte, []int) {
	return file_all_enum_proto_rawDescGZIP(), []int{2}
}

type MusicSortType int32

const (
	MusicSortType_MST_Unknown         MusicSortType = 0
	MusicSortType_MST_Created_At_Desc MusicSortType = 1
	MusicSortType_MST_Created_At_Asc  MusicSortType = 2
	MusicSortType_MST_Issue_Time_Desc MusicSortType = 3
	MusicSortType_MST_Issue_Time_Asc  MusicSortType = 4
)

// Enum value maps for MusicSortType.
var (
	MusicSortType_name = map[int32]string{
		0: "MST_Unknown",
		1: "MST_Created_At_Desc",
		2: "MST_Created_At_Asc",
		3: "MST_Issue_Time_Desc",
		4: "MST_Issue_Time_Asc",
	}
	MusicSortType_value = map[string]int32{
		"MST_Unknown":         0,
		"MST_Created_At_Desc": 1,
		"MST_Created_At_Asc":  2,
		"MST_Issue_Time_Desc": 3,
		"MST_Issue_Time_Asc":  4,
	}
)

func (x MusicSortType) Enum() *MusicSortType {
	p := new(MusicSortType)
	*p = x
	return p
}

func (x MusicSortType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MusicSortType) Descriptor() protoreflect.EnumDescriptor {
	return file_all_enum_proto_enumTypes[3].Descriptor()
}

func (MusicSortType) Type() protoreflect.EnumType {
	return &file_all_enum_proto_enumTypes[3]
}

func (x MusicSortType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MusicSortType.Descriptor instead.
func (MusicSortType) EnumDescriptor() ([]byte, []int) {
	return file_all_enum_proto_rawDescGZIP(), []int{3}
}

type TagBiz int32

const (
	TagBiz_TB_Unknown TagBiz = 0
	TagBiz_TB_Music   TagBiz = 1
)

// Enum value maps for TagBiz.
var (
	TagBiz_name = map[int32]string{
		0: "TB_Unknown",
		1: "TB_Music",
	}
	TagBiz_value = map[string]int32{
		"TB_Unknown": 0,
		"TB_Music":   1,
	}
)

func (x TagBiz) Enum() *TagBiz {
	p := new(TagBiz)
	*p = x
	return p
}

func (x TagBiz) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TagBiz) Descriptor() protoreflect.EnumDescriptor {
	return file_all_enum_proto_enumTypes[4].Descriptor()
}

func (TagBiz) Type() protoreflect.EnumType {
	return &file_all_enum_proto_enumTypes[4]
}

func (x TagBiz) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TagBiz.Descriptor instead.
func (TagBiz) EnumDescriptor() ([]byte, []int) {
	return file_all_enum_proto_rawDescGZIP(), []int{4}
}

type TagGroup int32

const (
	TagGroup_TG_Unknown         TagGroup = 0
	TagGroup_TG_MusicTheme      TagGroup = 1
	TagGroup_TG_MusicStyle      TagGroup = 2
	TagGroup_TG_MusicEmotion    TagGroup = 3
	TagGroup_TG_MusicHighlight  TagGroup = 4
	TagGroup_TG_MusicCollection TagGroup = 5
)

// Enum value maps for TagGroup.
var (
	TagGroup_name = map[int32]string{
		0: "TG_Unknown",
		1: "TG_MusicTheme",
		2: "TG_MusicStyle",
		3: "TG_MusicEmotion",
		4: "TG_MusicHighlight",
		5: "TG_MusicCollection",
	}
	TagGroup_value = map[string]int32{
		"TG_Unknown":         0,
		"TG_MusicTheme":      1,
		"TG_MusicStyle":      2,
		"TG_MusicEmotion":    3,
		"TG_MusicHighlight":  4,
		"TG_MusicCollection": 5,
	}
)

func (x TagGroup) Enum() *TagGroup {
	p := new(TagGroup)
	*p = x
	return p
}

func (x TagGroup) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TagGroup) Descriptor() protoreflect.EnumDescriptor {
	return file_all_enum_proto_enumTypes[5].Descriptor()
}

func (TagGroup) Type() protoreflect.EnumType {
	return &file_all_enum_proto_enumTypes[5]
}

func (x TagGroup) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TagGroup.Descriptor instead.
func (TagGroup) EnumDescriptor() ([]byte, []int) {
	return file_all_enum_proto_rawDescGZIP(), []int{5}
}

type TagType int32

const (
	TagType_TT_Unknown TagType = 0 // 10101
	// 10401
	TagType_TT_NcBridge TagType = 10401
)

// Enum value maps for TagType.
var (
	TagType_name = map[int32]string{
		0:     "TT_Unknown",
		10401: "TT_NcBridge",
	}
	TagType_value = map[string]int32{
		"TT_Unknown":  0,
		"TT_NcBridge": 10401,
	}
)

func (x TagType) Enum() *TagType {
	p := new(TagType)
	*p = x
	return p
}

func (x TagType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TagType) Descriptor() protoreflect.EnumDescriptor {
	return file_all_enum_proto_enumTypes[6].Descriptor()
}

func (TagType) Type() protoreflect.EnumType {
	return &file_all_enum_proto_enumTypes[6]
}

func (x TagType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TagType.Descriptor instead.
func (TagType) EnumDescriptor() ([]byte, []int) {
	return file_all_enum_proto_rawDescGZIP(), []int{6}
}

var File_all_enum_proto protoreflect.FileDescriptor

var file_all_enum_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x61, 0x6c, 0x6c, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x6f, 0x6e, 0x69, 0x6a, 0x1a, 0x09, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2a, 0x2b, 0x0a, 0x05, 0x41, 0x70, 0x70, 0x49, 0x64, 0x12, 0x11, 0x0a, 0x0d, 0x41, 0x70,
	0x70, 0x49, 0x64, 0x5f, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x0f, 0x0a,
	0x0b, 0x41, 0x70, 0x70, 0x49, 0x64, 0x5f, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x10, 0x01, 0x2a, 0x41,
	0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x46, 0x54,
	0x5f, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x54,
	0x5f, 0x4d, 0x70, 0x33, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x46, 0x54, 0x5f, 0x4c, 0x79, 0x72,
	0x69, 0x63, 0x73, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x54, 0x5f, 0x50, 0x6e, 0x67, 0x10,
	0x03, 0x2a, 0x4b, 0x0a, 0x0a, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0e, 0x0a, 0x0a, 0x41, 0x54, 0x5f, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12,
	0x0d, 0x0a, 0x09, 0x41, 0x54, 0x5f, 0x53, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x10, 0x01, 0x12, 0x0d,
	0x0a, 0x09, 0x41, 0x54, 0x5f, 0x57, 0x72, 0x69, 0x74, 0x65, 0x72, 0x10, 0x02, 0x12, 0x0f, 0x0a,
	0x0b, 0x41, 0x54, 0x5f, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x72, 0x10, 0x03, 0x2a, 0x82,
	0x01, 0x0a, 0x0d, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x53, 0x6f, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0f, 0x0a, 0x0b, 0x4d, 0x53, 0x54, 0x5f, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10,
	0x00, 0x12, 0x17, 0x0a, 0x13, 0x4d, 0x53, 0x54, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x41, 0x74, 0x5f, 0x44, 0x65, 0x73, 0x63, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x4d, 0x53,
	0x54, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x41, 0x74, 0x5f, 0x41, 0x73, 0x63,
	0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x4d, 0x53, 0x54, 0x5f, 0x49, 0x73, 0x73, 0x75, 0x65, 0x5f,
	0x54, 0x69, 0x6d, 0x65, 0x5f, 0x44, 0x65, 0x73, 0x63, 0x10, 0x03, 0x12, 0x16, 0x0a, 0x12, 0x4d,
	0x53, 0x54, 0x5f, 0x49, 0x73, 0x73, 0x75, 0x65, 0x5f, 0x54, 0x69, 0x6d, 0x65, 0x5f, 0x41, 0x73,
	0x63, 0x10, 0x04, 0x2a, 0x26, 0x0a, 0x06, 0x54, 0x61, 0x67, 0x42, 0x69, 0x7a, 0x12, 0x0e, 0x0a,
	0x0a, 0x54, 0x42, 0x5f, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x0c, 0x0a,
	0x08, 0x54, 0x42, 0x5f, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x10, 0x01, 0x2a, 0x84, 0x01, 0x0a, 0x08,
	0x54, 0x61, 0x67, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x47, 0x5f, 0x55,
	0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x54, 0x47, 0x5f, 0x4d,
	0x75, 0x73, 0x69, 0x63, 0x54, 0x68, 0x65, 0x6d, 0x65, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x54,
	0x47, 0x5f, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x10, 0x02, 0x12, 0x13,
	0x0a, 0x0f, 0x54, 0x47, 0x5f, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x45, 0x6d, 0x6f, 0x74, 0x69, 0x6f,
	0x6e, 0x10, 0x03, 0x12, 0x15, 0x0a, 0x11, 0x54, 0x47, 0x5f, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x48,
	0x69, 0x67, 0x68, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x10, 0x04, 0x12, 0x16, 0x0a, 0x12, 0x54, 0x47,
	0x5f, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x10, 0x05, 0x2a, 0x2b, 0x0a, 0x07, 0x54, 0x61, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a,
	0x0a, 0x54, 0x54, 0x5f, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x10, 0x0a,
	0x0b, 0x54, 0x54, 0x5f, 0x4e, 0x63, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x10, 0xa1, 0x51, 0x42,
	0x10, 0x5a, 0x0e, 0x6f, 0x6e, 0x69, 0x6a, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x61, 0x70,
	0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_all_enum_proto_rawDescOnce sync.Once
	file_all_enum_proto_rawDescData = file_all_enum_proto_rawDesc
)

func file_all_enum_proto_rawDescGZIP() []byte {
	file_all_enum_proto_rawDescOnce.Do(func() {
		file_all_enum_proto_rawDescData = protoimpl.X.CompressGZIP(file_all_enum_proto_rawDescData)
	})
	return file_all_enum_proto_rawDescData
}

var file_all_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_all_enum_proto_goTypes = []interface{}{
	(AppId)(0),         // 0: onij.AppId
	(FileType)(0),      // 1: onij.FileType
	(ArtistType)(0),    // 2: onij.ArtistType
	(MusicSortType)(0), // 3: onij.MusicSortType
	(TagBiz)(0),        // 4: onij.TagBiz
	(TagGroup)(0),      // 5: onij.TagGroup
	(TagType)(0),       // 6: onij.TagType
}
var file_all_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_all_enum_proto_init() }
func file_all_enum_proto_init() {
	if File_all_enum_proto != nil {
		return
	}
	file_api_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_all_enum_proto_rawDesc,
			NumEnums:      7,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_all_enum_proto_goTypes,
		DependencyIndexes: file_all_enum_proto_depIdxs,
		EnumInfos:         file_all_enum_proto_enumTypes,
	}.Build()
	File_all_enum_proto = out.File
	file_all_enum_proto_rawDesc = nil
	file_all_enum_proto_goTypes = nil
	file_all_enum_proto_depIdxs = nil
}
