// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v5.28.3
// source: all_model.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MusicDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MusicDetail) Reset() {
	*x = MusicDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_model_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MusicDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MusicDetail) ProtoMessage() {}

func (x *MusicDetail) ProtoReflect() protoreflect.Message {
	mi := &file_all_model_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MusicDetail.ProtoReflect.Descriptor instead.
func (*MusicDetail) Descriptor() ([]byte, []int) {
	return file_all_model_proto_rawDescGZIP(), []int{0}
}

type AlbumDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AlbumDetail) Reset() {
	*x = AlbumDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_model_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlbumDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlbumDetail) ProtoMessage() {}

func (x *AlbumDetail) ProtoReflect() protoreflect.Message {
	mi := &file_all_model_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlbumDetail.ProtoReflect.Descriptor instead.
func (*AlbumDetail) Descriptor() ([]byte, []int) {
	return file_all_model_proto_rawDescGZIP(), []int{1}
}

var File_all_model_proto protoreflect.FileDescriptor

var file_all_model_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x61, 0x6c, 0x6c, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x6f, 0x6e, 0x69, 0x6a, 0x1a, 0x09, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x0d, 0x0a, 0x0b, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x22, 0x0d, 0x0a, 0x0b, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x42, 0x10, 0x5a, 0x0e, 0x6f, 0x6e, 0x69, 0x6a, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x61,
	0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_all_model_proto_rawDescOnce sync.Once
	file_all_model_proto_rawDescData = file_all_model_proto_rawDesc
)

func file_all_model_proto_rawDescGZIP() []byte {
	file_all_model_proto_rawDescOnce.Do(func() {
		file_all_model_proto_rawDescData = protoimpl.X.CompressGZIP(file_all_model_proto_rawDescData)
	})
	return file_all_model_proto_rawDescData
}

var file_all_model_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_all_model_proto_goTypes = []interface{}{
	(*MusicDetail)(nil), // 0: onij.MusicDetail
	(*AlbumDetail)(nil), // 1: onij.AlbumDetail
}
var file_all_model_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_all_model_proto_init() }
func file_all_model_proto_init() {
	if File_all_model_proto != nil {
		return
	}
	file_api_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_all_model_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MusicDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_all_model_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlbumDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_all_model_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_all_model_proto_goTypes,
		DependencyIndexes: file_all_model_proto_depIdxs,
		MessageInfos:      file_all_model_proto_msgTypes,
	}.Build()
	File_all_model_proto = out.File
	file_all_model_proto_rawDesc = nil
	file_all_model_proto_goTypes = nil
	file_all_model_proto_depIdxs = nil
}
