// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v4.25.3
// source: all_enum.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileType int32

const (
	FileType_FT_Unknown    FileType = 0
	FileType_FT_Pdf        FileType = 1
	FileType_FT_Word       FileType = 2
	FileType_FT_Excel      FileType = 3
	FileType_FT_PowerPoint FileType = 4
	FileType_FT_Image      FileType = 5
	FileType_FT_Video      FileType = 6
	FileType_FT_Audio      FileType = 7
	FileType_FT_Text       FileType = 8
	FileType_FT_Archive    FileType = 9
	FileType_FT_Code       FileType = 10
	FileType_FT_CSV        FileType = 11
	FileType_FT_Executable FileType = 12
	FileType_FT_Folder     FileType = 99
)

// Enum value maps for FileType.
var (
	FileType_name = map[int32]string{
		0:  "FT_Unknown",
		1:  "FT_Pdf",
		2:  "FT_Word",
		3:  "FT_Excel",
		4:  "FT_PowerPoint",
		5:  "FT_Image",
		6:  "FT_Video",
		7:  "FT_Audio",
		8:  "FT_Text",
		9:  "FT_Archive",
		10: "FT_Code",
		11: "FT_CSV",
		12: "FT_Executable",
		99: "FT_Folder",
	}
	FileType_value = map[string]int32{
		"FT_Unknown":    0,
		"FT_Pdf":        1,
		"FT_Word":       2,
		"FT_Excel":      3,
		"FT_PowerPoint": 4,
		"FT_Image":      5,
		"FT_Video":      6,
		"FT_Audio":      7,
		"FT_Text":       8,
		"FT_Archive":    9,
		"FT_Code":       10,
		"FT_CSV":        11,
		"FT_Executable": 12,
		"FT_Folder":     99,
	}
)

func (x FileType) Enum() *FileType {
	p := new(FileType)
	*p = x
	return p
}

func (x FileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileType) Descriptor() protoreflect.EnumDescriptor {
	return file_all_enum_proto_enumTypes[0].Descriptor()
}

func (FileType) Type() protoreflect.EnumType {
	return &file_all_enum_proto_enumTypes[0]
}

func (x FileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileType.Descriptor instead.
func (FileType) EnumDescriptor() ([]byte, []int) {
	return file_all_enum_proto_rawDescGZIP(), []int{0}
}

type ArtistType int32

const (
	ArtistType_ATT_Unknown  ArtistType = 0
	ArtistType_ATT_Artist   ArtistType = 1
	ArtistType_ATT_Writer   ArtistType = 2
	ArtistType_ATT_Composer ArtistType = 3
)

// Enum value maps for ArtistType.
var (
	ArtistType_name = map[int32]string{
		0: "ATT_Unknown",
		1: "ATT_Artist",
		2: "ATT_Writer",
		3: "ATT_Composer",
	}
	ArtistType_value = map[string]int32{
		"ATT_Unknown":  0,
		"ATT_Artist":   1,
		"ATT_Writer":   2,
		"ATT_Composer": 3,
	}
)

func (x ArtistType) Enum() *ArtistType {
	p := new(ArtistType)
	*p = x
	return p
}

func (x ArtistType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArtistType) Descriptor() protoreflect.EnumDescriptor {
	return file_all_enum_proto_enumTypes[1].Descriptor()
}

func (ArtistType) Type() protoreflect.EnumType {
	return &file_all_enum_proto_enumTypes[1]
}

func (x ArtistType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArtistType.Descriptor instead.
func (ArtistType) EnumDescriptor() ([]byte, []int) {
	return file_all_enum_proto_rawDescGZIP(), []int{1}
}

// 专辑类型
type AlbumType int32

const (
	AlbumType_ALT_Unknown AlbumType = 0
	AlbumType_ALT_Studio  AlbumType = 1 // 录音室专辑
	AlbumType_ALT_Live    AlbumType = 2 // 现场专辑
	AlbumType_ALT_OST     AlbumType = 3 // 原声带专辑
	AlbumType_ALT_Cover   AlbumType = 4 // 翻唱专辑
	AlbumType_ALT_Other   AlbumType = 99
)

// Enum value maps for AlbumType.
var (
	AlbumType_name = map[int32]string{
		0:  "ALT_Unknown",
		1:  "ALT_Studio",
		2:  "ALT_Live",
		3:  "ALT_OST",
		4:  "ALT_Cover",
		99: "ALT_Other",
	}
	AlbumType_value = map[string]int32{
		"ALT_Unknown": 0,
		"ALT_Studio":  1,
		"ALT_Live":    2,
		"ALT_OST":     3,
		"ALT_Cover":   4,
		"ALT_Other":   99,
	}
)

func (x AlbumType) Enum() *AlbumType {
	p := new(AlbumType)
	*p = x
	return p
}

func (x AlbumType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlbumType) Descriptor() protoreflect.EnumDescriptor {
	return file_all_enum_proto_enumTypes[2].Descriptor()
}

func (AlbumType) Type() protoreflect.EnumType {
	return &file_all_enum_proto_enumTypes[2]
}

func (x AlbumType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlbumType.Descriptor instead.
func (AlbumType) EnumDescriptor() ([]byte, []int) {
	return file_all_enum_proto_rawDescGZIP(), []int{2}
}

type AudioQuality int32

const (
	AudioQuality_AQ_Unknown AudioQuality = 0
	AudioQuality_AQ_Low     AudioQuality = 1
)

// Enum value maps for AudioQuality.
var (
	AudioQuality_name = map[int32]string{
		0: "AQ_Unknown",
		1: "AQ_Low",
	}
	AudioQuality_value = map[string]int32{
		"AQ_Unknown": 0,
		"AQ_Low":     1,
	}
)

func (x AudioQuality) Enum() *AudioQuality {
	p := new(AudioQuality)
	*p = x
	return p
}

func (x AudioQuality) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AudioQuality) Descriptor() protoreflect.EnumDescriptor {
	return file_all_enum_proto_enumTypes[3].Descriptor()
}

func (AudioQuality) Type() protoreflect.EnumType {
	return &file_all_enum_proto_enumTypes[3]
}

func (x AudioQuality) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AudioQuality.Descriptor instead.
func (AudioQuality) EnumDescriptor() ([]byte, []int) {
	return file_all_enum_proto_rawDescGZIP(), []int{3}
}

type PerformType int32

const (
	PerformType_PFT_Unknown PerformType = 0
)

// Enum value maps for PerformType.
var (
	PerformType_name = map[int32]string{
		0: "PFT_Unknown",
	}
	PerformType_value = map[string]int32{
		"PFT_Unknown": 0,
	}
)

func (x PerformType) Enum() *PerformType {
	p := new(PerformType)
	*p = x
	return p
}

func (x PerformType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PerformType) Descriptor() protoreflect.EnumDescriptor {
	return file_all_enum_proto_enumTypes[4].Descriptor()
}

func (PerformType) Type() protoreflect.EnumType {
	return &file_all_enum_proto_enumTypes[4]
}

func (x PerformType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PerformType.Descriptor instead.
func (PerformType) EnumDescriptor() ([]byte, []int) {
	return file_all_enum_proto_rawDescGZIP(), []int{4}
}

// 标签业务
type TagBiz int32

const (
	TagBiz_TB_Unknown TagBiz = 0
	TagBiz_TB_Music   TagBiz = 1
)

// Enum value maps for TagBiz.
var (
	TagBiz_name = map[int32]string{
		0: "TB_Unknown",
		1: "TB_Music",
	}
	TagBiz_value = map[string]int32{
		"TB_Unknown": 0,
		"TB_Music":   1,
	}
)

func (x TagBiz) Enum() *TagBiz {
	p := new(TagBiz)
	*p = x
	return p
}

func (x TagBiz) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TagBiz) Descriptor() protoreflect.EnumDescriptor {
	return file_all_enum_proto_enumTypes[5].Descriptor()
}

func (TagBiz) Type() protoreflect.EnumType {
	return &file_all_enum_proto_enumTypes[5]
}

func (x TagBiz) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TagBiz.Descriptor instead.
func (TagBiz) EnumDescriptor() ([]byte, []int) {
	return file_all_enum_proto_rawDescGZIP(), []int{5}
}

// 标签组
type TagGroup int32

const (
	TagGroup_TG_Unknown         TagGroup = 0
	TagGroup_TG_MusicTheme      TagGroup = 101
	TagGroup_TG_MusicStyle      TagGroup = 102
	TagGroup_TG_MusicEmotion    TagGroup = 103
	TagGroup_TG_MusicHighlight  TagGroup = 104
	TagGroup_TG_MusicCollection TagGroup = 105
	TagGroup_TG_ArtistStar      TagGroup = 120
)

// Enum value maps for TagGroup.
var (
	TagGroup_name = map[int32]string{
		0:   "TG_Unknown",
		101: "TG_MusicTheme",
		102: "TG_MusicStyle",
		103: "TG_MusicEmotion",
		104: "TG_MusicHighlight",
		105: "TG_MusicCollection",
		120: "TG_ArtistStar",
	}
	TagGroup_value = map[string]int32{
		"TG_Unknown":         0,
		"TG_MusicTheme":      101,
		"TG_MusicStyle":      102,
		"TG_MusicEmotion":    103,
		"TG_MusicHighlight":  104,
		"TG_MusicCollection": 105,
		"TG_ArtistStar":      120,
	}
)

func (x TagGroup) Enum() *TagGroup {
	p := new(TagGroup)
	*p = x
	return p
}

func (x TagGroup) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TagGroup) Descriptor() protoreflect.EnumDescriptor {
	return file_all_enum_proto_enumTypes[6].Descriptor()
}

func (TagGroup) Type() protoreflect.EnumType {
	return &file_all_enum_proto_enumTypes[6]
}

func (x TagGroup) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TagGroup.Descriptor instead.
func (TagGroup) EnumDescriptor() ([]byte, []int) {
	return file_all_enum_proto_rawDescGZIP(), []int{6}
}

// 标签类型
type TagType int32

const (
	TagType_TT_Unknown TagType = 0 // 10101
	// 10401
	TagType_TT_NcBridge TagType = 10401
	// 12001
	TagType_TT_Star TagType = 12001
)

// Enum value maps for TagType.
var (
	TagType_name = map[int32]string{
		0:     "TT_Unknown",
		10401: "TT_NcBridge",
		12001: "TT_Star",
	}
	TagType_value = map[string]int32{
		"TT_Unknown":  0,
		"TT_NcBridge": 10401,
		"TT_Star":     12001,
	}
)

func (x TagType) Enum() *TagType {
	p := new(TagType)
	*p = x
	return p
}

func (x TagType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TagType) Descriptor() protoreflect.EnumDescriptor {
	return file_all_enum_proto_enumTypes[7].Descriptor()
}

func (TagType) Type() protoreflect.EnumType {
	return &file_all_enum_proto_enumTypes[7]
}

func (x TagType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TagType.Descriptor instead.
func (TagType) EnumDescriptor() ([]byte, []int) {
	return file_all_enum_proto_rawDescGZIP(), []int{7}
}

// 资源类型
type ResourceType int32

const (
	ResourceType_RT_Unknown ResourceType = 0
	ResourceType_RT_Artist  ResourceType = 1
	ResourceType_RT_Music   ResourceType = 2
	ResourceType_RT_Album   ResourceType = 3
)

// Enum value maps for ResourceType.
var (
	ResourceType_name = map[int32]string{
		0: "RT_Unknown",
		1: "RT_Artist",
		2: "RT_Music",
		3: "RT_Album",
	}
	ResourceType_value = map[string]int32{
		"RT_Unknown": 0,
		"RT_Artist":  1,
		"RT_Music":   2,
		"RT_Album":   3,
	}
)

func (x ResourceType) Enum() *ResourceType {
	p := new(ResourceType)
	*p = x
	return p
}

func (x ResourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_all_enum_proto_enumTypes[8].Descriptor()
}

func (ResourceType) Type() protoreflect.EnumType {
	return &file_all_enum_proto_enumTypes[8]
}

func (x ResourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceType.Descriptor instead.
func (ResourceType) EnumDescriptor() ([]byte, []int) {
	return file_all_enum_proto_rawDescGZIP(), []int{8}
}

// 练习类型
type PracticeType int32

const (
	PracticeType_PT_Unknown           PracticeType = 0
	PracticeType_PT_AnaerobicExercise PracticeType = 1
	PracticeType_PT_AerobicExercise   PracticeType = 2
	PracticeType_PT_Reading           PracticeType = 3
	PracticeType_PT_Language          PracticeType = 4
	PracticeType_PT_Game              PracticeType = 5
	PracticeType_PT_Piano             PracticeType = 6
	PracticeType_PT_Flute             PracticeType = 7
	PracticeType_PT_Singing           PracticeType = 8
	PracticeType_PT_Other             PracticeType = 99
)

// Enum value maps for PracticeType.
var (
	PracticeType_name = map[int32]string{
		0:  "PT_Unknown",
		1:  "PT_AnaerobicExercise",
		2:  "PT_AerobicExercise",
		3:  "PT_Reading",
		4:  "PT_Language",
		5:  "PT_Game",
		6:  "PT_Piano",
		7:  "PT_Flute",
		8:  "PT_Singing",
		99: "PT_Other",
	}
	PracticeType_value = map[string]int32{
		"PT_Unknown":           0,
		"PT_AnaerobicExercise": 1,
		"PT_AerobicExercise":   2,
		"PT_Reading":           3,
		"PT_Language":          4,
		"PT_Game":              5,
		"PT_Piano":             6,
		"PT_Flute":             7,
		"PT_Singing":           8,
		"PT_Other":             99,
	}
)

func (x PracticeType) Enum() *PracticeType {
	p := new(PracticeType)
	*p = x
	return p
}

func (x PracticeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PracticeType) Descriptor() protoreflect.EnumDescriptor {
	return file_all_enum_proto_enumTypes[9].Descriptor()
}

func (PracticeType) Type() protoreflect.EnumType {
	return &file_all_enum_proto_enumTypes[9]
}

func (x PracticeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PracticeType.Descriptor instead.
func (PracticeType) EnumDescriptor() ([]byte, []int) {
	return file_all_enum_proto_rawDescGZIP(), []int{9}
}

var File_all_enum_proto protoreflect.FileDescriptor

var file_all_enum_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x61, 0x6c, 0x6c, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x6f, 0x6e, 0x69, 0x6a, 0x2a, 0xd6, 0x01, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x46, 0x54, 0x5f, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77,
	0x6e, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x54, 0x5f, 0x50, 0x64, 0x66, 0x10, 0x01, 0x12,
	0x0b, 0x0a, 0x07, 0x46, 0x54, 0x5f, 0x57, 0x6f, 0x72, 0x64, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08,
	0x46, 0x54, 0x5f, 0x45, 0x78, 0x63, 0x65, 0x6c, 0x10, 0x03, 0x12, 0x11, 0x0a, 0x0d, 0x46, 0x54,
	0x5f, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x10, 0x04, 0x12, 0x0c, 0x0a,
	0x08, 0x46, 0x54, 0x5f, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x10, 0x05, 0x12, 0x0c, 0x0a, 0x08, 0x46,
	0x54, 0x5f, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x10, 0x06, 0x12, 0x0c, 0x0a, 0x08, 0x46, 0x54, 0x5f,
	0x41, 0x75, 0x64, 0x69, 0x6f, 0x10, 0x07, 0x12, 0x0b, 0x0a, 0x07, 0x46, 0x54, 0x5f, 0x54, 0x65,
	0x78, 0x74, 0x10, 0x08, 0x12, 0x0e, 0x0a, 0x0a, 0x46, 0x54, 0x5f, 0x41, 0x72, 0x63, 0x68, 0x69,
	0x76, 0x65, 0x10, 0x09, 0x12, 0x0b, 0x0a, 0x07, 0x46, 0x54, 0x5f, 0x43, 0x6f, 0x64, 0x65, 0x10,
	0x0a, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x54, 0x5f, 0x43, 0x53, 0x56, 0x10, 0x0b, 0x12, 0x11, 0x0a,
	0x0d, 0x46, 0x54, 0x5f, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x10, 0x0c,
	0x12, 0x0d, 0x0a, 0x09, 0x46, 0x54, 0x5f, 0x46, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x10, 0x63, 0x2a,
	0x4f, 0x0a, 0x0a, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a,
	0x0b, 0x41, 0x54, 0x54, 0x5f, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x0e,
	0x0a, 0x0a, 0x41, 0x54, 0x54, 0x5f, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x10, 0x01, 0x12, 0x0e,
	0x0a, 0x0a, 0x41, 0x54, 0x54, 0x5f, 0x57, 0x72, 0x69, 0x74, 0x65, 0x72, 0x10, 0x02, 0x12, 0x10,
	0x0a, 0x0c, 0x41, 0x54, 0x54, 0x5f, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x72, 0x10, 0x03,
	0x2a, 0x65, 0x0a, 0x09, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a,
	0x0b, 0x41, 0x4c, 0x54, 0x5f, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x0e,
	0x0a, 0x0a, 0x41, 0x4c, 0x54, 0x5f, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x10, 0x01, 0x12, 0x0c,
	0x0a, 0x08, 0x41, 0x4c, 0x54, 0x5f, 0x4c, 0x69, 0x76, 0x65, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07,
	0x41, 0x4c, 0x54, 0x5f, 0x4f, 0x53, 0x54, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x4c, 0x54,
	0x5f, 0x43, 0x6f, 0x76, 0x65, 0x72, 0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x4c, 0x54, 0x5f,
	0x4f, 0x74, 0x68, 0x65, 0x72, 0x10, 0x63, 0x2a, 0x2a, 0x0a, 0x0c, 0x41, 0x75, 0x64, 0x69, 0x6f,
	0x51, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x0e, 0x0a, 0x0a, 0x41, 0x51, 0x5f, 0x55, 0x6e,
	0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x51, 0x5f, 0x4c, 0x6f,
	0x77, 0x10, 0x01, 0x2a, 0x1e, 0x0a, 0x0b, 0x50, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x50, 0x46, 0x54, 0x5f, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77,
	0x6e, 0x10, 0x00, 0x2a, 0x26, 0x0a, 0x06, 0x54, 0x61, 0x67, 0x42, 0x69, 0x7a, 0x12, 0x0e, 0x0a,
	0x0a, 0x54, 0x42, 0x5f, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x0c, 0x0a,
	0x08, 0x54, 0x42, 0x5f, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x10, 0x01, 0x2a, 0x97, 0x01, 0x0a, 0x08,
	0x54, 0x61, 0x67, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x47, 0x5f, 0x55,
	0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x54, 0x47, 0x5f, 0x4d,
	0x75, 0x73, 0x69, 0x63, 0x54, 0x68, 0x65, 0x6d, 0x65, 0x10, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x54,
	0x47, 0x5f, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x10, 0x66, 0x12, 0x13,
	0x0a, 0x0f, 0x54, 0x47, 0x5f, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x45, 0x6d, 0x6f, 0x74, 0x69, 0x6f,
	0x6e, 0x10, 0x67, 0x12, 0x15, 0x0a, 0x11, 0x54, 0x47, 0x5f, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x48,
	0x69, 0x67, 0x68, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x10, 0x68, 0x12, 0x16, 0x0a, 0x12, 0x54, 0x47,
	0x5f, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x10, 0x69, 0x12, 0x11, 0x0a, 0x0d, 0x54, 0x47, 0x5f, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x53,
	0x74, 0x61, 0x72, 0x10, 0x78, 0x2a, 0x39, 0x0a, 0x07, 0x54, 0x61, 0x67, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x54, 0x5f, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00,
	0x12, 0x10, 0x0a, 0x0b, 0x54, 0x54, 0x5f, 0x4e, 0x63, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x10,
	0xa1, 0x51, 0x12, 0x0c, 0x0a, 0x07, 0x54, 0x54, 0x5f, 0x53, 0x74, 0x61, 0x72, 0x10, 0xe1, 0x5d,
	0x2a, 0x49, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x54, 0x5f, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00,
	0x12, 0x0d, 0x0a, 0x09, 0x52, 0x54, 0x5f, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x10, 0x01, 0x12,
	0x0c, 0x0a, 0x08, 0x52, 0x54, 0x5f, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x10, 0x02, 0x12, 0x0c, 0x0a,
	0x08, 0x52, 0x54, 0x5f, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x10, 0x03, 0x2a, 0xb8, 0x01, 0x0a, 0x0c,
	0x50, 0x72, 0x61, 0x63, 0x74, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x0a,
	0x50, 0x54, 0x5f, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14,
	0x50, 0x54, 0x5f, 0x41, 0x6e, 0x61, 0x65, 0x72, 0x6f, 0x62, 0x69, 0x63, 0x45, 0x78, 0x65, 0x72,
	0x63, 0x69, 0x73, 0x65, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x50, 0x54, 0x5f, 0x41, 0x65, 0x72,
	0x6f, 0x62, 0x69, 0x63, 0x45, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x10, 0x02, 0x12, 0x0e,
	0x0a, 0x0a, 0x50, 0x54, 0x5f, 0x52, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x10, 0x03, 0x12, 0x0f,
	0x0a, 0x0b, 0x50, 0x54, 0x5f, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x10, 0x04, 0x12,
	0x0b, 0x0a, 0x07, 0x50, 0x54, 0x5f, 0x47, 0x61, 0x6d, 0x65, 0x10, 0x05, 0x12, 0x0c, 0x0a, 0x08,
	0x50, 0x54, 0x5f, 0x50, 0x69, 0x61, 0x6e, 0x6f, 0x10, 0x06, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x54,
	0x5f, 0x46, 0x6c, 0x75, 0x74, 0x65, 0x10, 0x07, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x54, 0x5f, 0x53,
	0x69, 0x6e, 0x67, 0x69, 0x6e, 0x67, 0x10, 0x08, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x54, 0x5f, 0x4f,
	0x74, 0x68, 0x65, 0x72, 0x10, 0x63, 0x42, 0x10, 0x5a, 0x0e, 0x6f, 0x6e, 0x69, 0x6a, 0x2f, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_all_enum_proto_rawDescOnce sync.Once
	file_all_enum_proto_rawDescData = file_all_enum_proto_rawDesc
)

func file_all_enum_proto_rawDescGZIP() []byte {
	file_all_enum_proto_rawDescOnce.Do(func() {
		file_all_enum_proto_rawDescData = protoimpl.X.CompressGZIP(file_all_enum_proto_rawDescData)
	})
	return file_all_enum_proto_rawDescData
}

var file_all_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 10)
var file_all_enum_proto_goTypes = []interface{}{
	(FileType)(0),     // 0: onij.FileType
	(ArtistType)(0),   // 1: onij.ArtistType
	(AlbumType)(0),    // 2: onij.AlbumType
	(AudioQuality)(0), // 3: onij.AudioQuality
	(PerformType)(0),  // 4: onij.PerformType
	(TagBiz)(0),       // 5: onij.TagBiz
	(TagGroup)(0),     // 6: onij.TagGroup
	(TagType)(0),      // 7: onij.TagType
	(ResourceType)(0), // 8: onij.ResourceType
	(PracticeType)(0), // 9: onij.PracticeType
}
var file_all_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_all_enum_proto_init() }
func file_all_enum_proto_init() {
	if File_all_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_all_enum_proto_rawDesc,
			NumEnums:      10,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_all_enum_proto_goTypes,
		DependencyIndexes: file_all_enum_proto_depIdxs,
		EnumInfos:         file_all_enum_proto_enumTypes,
	}.Build()
	File_all_enum_proto = out.File
	file_all_enum_proto_rawDesc = nil
	file_all_enum_proto_goTypes = nil
	file_all_enum_proto_depIdxs = nil
}
