// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v5.28.3
// source: all_model.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Music struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" form:"id" query:"id"`
	Name          string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" form:"name" query:"name"`
	Artists       []*Artist `protobuf:"bytes,3,rep,name=artists,proto3" json:"artists,omitempty" form:"artists" query:"artists"`
	IssueTime     int32     `protobuf:"varint,4,opt,name=issue_time,json=issueTime,proto3" json:"issue_time,omitempty" form:"issue_time" query:"issue_time"`
	MvUrl         string    `protobuf:"bytes,5,opt,name=mv_url,json=mvUrl,proto3" json:"mv_url,omitempty" form:"mv_url" query:"mv_url"`
	Mp3FileUrl    string    `protobuf:"bytes,21,opt,name=mp3_file_url,json=mp3FileUrl,proto3" json:"mp3_file_url,omitempty" form:"mp3_file_url" query:"mp3_file_url"`
	LyricsFileUrl string    `protobuf:"bytes,22,opt,name=lyrics_file_url,json=lyricsFileUrl,proto3" json:"lyrics_file_url,omitempty" form:"lyrics_file_url" query:"lyrics_file_url"`
	Album         *Album    `protobuf:"bytes,30,opt,name=album,proto3" json:"album,omitempty" form:"album" query:"album"`
	Tags          []*Tag    `protobuf:"bytes,31,rep,name=tags,proto3" json:"tags,omitempty" form:"tags" query:"tags"`
}

func (x *Music) Reset() {
	*x = Music{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_model_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Music) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Music) ProtoMessage() {}

func (x *Music) ProtoReflect() protoreflect.Message {
	mi := &file_all_model_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Music.ProtoReflect.Descriptor instead.
func (*Music) Descriptor() ([]byte, []int) {
	return file_all_model_proto_rawDescGZIP(), []int{0}
}

func (x *Music) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Music) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Music) GetArtists() []*Artist {
	if x != nil {
		return x.Artists
	}
	return nil
}

func (x *Music) GetIssueTime() int32 {
	if x != nil {
		return x.IssueTime
	}
	return 0
}

func (x *Music) GetMvUrl() string {
	if x != nil {
		return x.MvUrl
	}
	return ""
}

func (x *Music) GetMp3FileUrl() string {
	if x != nil {
		return x.Mp3FileUrl
	}
	return ""
}

func (x *Music) GetLyricsFileUrl() string {
	if x != nil {
		return x.LyricsFileUrl
	}
	return ""
}

func (x *Music) GetAlbum() *Album {
	if x != nil {
		return x.Album
	}
	return nil
}

func (x *Music) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Tag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" form:"id" query:"id"`
	ResourceId   int64        `protobuf:"varint,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty" form:"resource_id" query:"resource_id"`
	ResourceType ResourceType `protobuf:"varint,3,opt,name=resource_type,json=resourceType,proto3,enum=onij.ResourceType" json:"resource_type,omitempty" form:"resource_type" query:"resource_type"`
	TagBiz       TagBiz       `protobuf:"varint,4,opt,name=tag_biz,json=tagBiz,proto3,enum=onij.TagBiz" json:"tag_biz,omitempty" form:"tag_biz" query:"tag_biz"`
	TagGroup     TagGroup     `protobuf:"varint,5,opt,name=tag_group,json=tagGroup,proto3,enum=onij.TagGroup" json:"tag_group,omitempty" form:"tag_group" query:"tag_group"`
	TagType      TagType      `protobuf:"varint,6,opt,name=tag_type,json=tagType,proto3,enum=onij.TagType" json:"tag_type,omitempty" form:"tag_type" query:"tag_type"`
	TargetId     int64        `protobuf:"varint,7,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty" form:"target_id" query:"target_id"`
	TargetType   int32        `protobuf:"varint,8,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty" form:"target_type" query:"target_type"`
	Extra        string       `protobuf:"bytes,9,opt,name=extra,proto3" json:"extra,omitempty" form:"extra" query:"extra"`
}

func (x *Tag) Reset() {
	*x = Tag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_model_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_all_model_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_all_model_proto_rawDescGZIP(), []int{1}
}

func (x *Tag) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tag) GetResourceId() int64 {
	if x != nil {
		return x.ResourceId
	}
	return 0
}

func (x *Tag) GetResourceType() ResourceType {
	if x != nil {
		return x.ResourceType
	}
	return ResourceType_RT_Unknown
}

func (x *Tag) GetTagBiz() TagBiz {
	if x != nil {
		return x.TagBiz
	}
	return TagBiz_TB_Unknown
}

func (x *Tag) GetTagGroup() TagGroup {
	if x != nil {
		return x.TagGroup
	}
	return TagGroup_TG_Unknown
}

func (x *Tag) GetTagType() TagType {
	if x != nil {
		return x.TagType
	}
	return TagType_TT_Unknown
}

func (x *Tag) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *Tag) GetTargetType() int32 {
	if x != nil {
		return x.TargetType
	}
	return 0
}

func (x *Tag) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

type Artist struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" form:"id" query:"id"`
	Name          string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" form:"name" query:"name"`
	AvatarFileUrl string       `protobuf:"bytes,3,opt,name=avatar_file_url,json=avatarFileUrl,proto3" json:"avatar_file_url,omitempty" form:"avatar_file_url" query:"avatar_file_url"`
	ArtistTypes   []ArtistType `protobuf:"varint,4,rep,packed,name=artist_types,json=artistTypes,proto3,enum=onij.ArtistType" json:"artist_types,omitempty" form:"artist_types" query:"artist_types"`
}

func (x *Artist) Reset() {
	*x = Artist{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_model_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Artist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artist) ProtoMessage() {}

func (x *Artist) ProtoReflect() protoreflect.Message {
	mi := &file_all_model_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artist.ProtoReflect.Descriptor instead.
func (*Artist) Descriptor() ([]byte, []int) {
	return file_all_model_proto_rawDescGZIP(), []int{2}
}

func (x *Artist) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Artist) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Artist) GetAvatarFileUrl() string {
	if x != nil {
		return x.AvatarFileUrl
	}
	return ""
}

func (x *Artist) GetArtistTypes() []ArtistType {
	if x != nil {
		return x.ArtistTypes
	}
	return nil
}

type Album struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" form:"id" query:"id"`
	Name         string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" form:"name" query:"name"`
	Profile      string    `protobuf:"bytes,3,opt,name=profile,proto3" json:"profile,omitempty" form:"profile" query:"profile"`
	AlbumType    AlbumType `protobuf:"varint,4,opt,name=album_type,json=albumType,proto3,enum=onij.AlbumType" json:"album_type,omitempty" form:"album_type" query:"album_type"`
	Artists      []*Artist `protobuf:"bytes,5,rep,name=artists,proto3" json:"artists,omitempty" form:"artists" query:"artists"`
	IssueTime    int32     `protobuf:"varint,6,opt,name=issue_time,json=issueTime,proto3" json:"issue_time,omitempty" form:"issue_time" query:"issue_time"`
	CoverFileUrl string    `protobuf:"bytes,7,opt,name=cover_file_url,json=coverFileUrl,proto3" json:"cover_file_url,omitempty" form:"cover_file_url" query:"cover_file_url"`
	LiveUrl      string    `protobuf:"bytes,8,opt,name=live_url,json=liveUrl,proto3" json:"live_url,omitempty" form:"live_url" query:"live_url"`
}

func (x *Album) Reset() {
	*x = Album{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_model_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Album) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Album) ProtoMessage() {}

func (x *Album) ProtoReflect() protoreflect.Message {
	mi := &file_all_model_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Album.ProtoReflect.Descriptor instead.
func (*Album) Descriptor() ([]byte, []int) {
	return file_all_model_proto_rawDescGZIP(), []int{3}
}

func (x *Album) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Album) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Album) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *Album) GetAlbumType() AlbumType {
	if x != nil {
		return x.AlbumType
	}
	return AlbumType_ALT_Unknown
}

func (x *Album) GetArtists() []*Artist {
	if x != nil {
		return x.Artists
	}
	return nil
}

func (x *Album) GetIssueTime() int32 {
	if x != nil {
		return x.IssueTime
	}
	return 0
}

func (x *Album) GetCoverFileUrl() string {
	if x != nil {
		return x.CoverFileUrl
	}
	return ""
}

func (x *Album) GetLiveUrl() string {
	if x != nil {
		return x.LiveUrl
	}
	return ""
}

type AlbumMusic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" form:"name" query:"name"`
	TimeLength  int32  `protobuf:"varint,2,opt,name=time_length,json=timeLength,proto3" json:"time_length,omitempty" form:"time_length" query:"time_length"`
	MusicId     int64  `protobuf:"varint,3,opt,name=music_id,json=musicId,proto3" json:"music_id,omitempty" form:"music_id" query:"music_id"`
	AlbumId     int64  `protobuf:"varint,4,opt,name=album_id,json=albumId,proto3" json:"album_id,omitempty" form:"album_id" query:"album_id"`
	IsAvailable bool   `protobuf:"varint,5,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty" form:"is_available" query:"is_available"`
}

func (x *AlbumMusic) Reset() {
	*x = AlbumMusic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_model_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlbumMusic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlbumMusic) ProtoMessage() {}

func (x *AlbumMusic) ProtoReflect() protoreflect.Message {
	mi := &file_all_model_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlbumMusic.ProtoReflect.Descriptor instead.
func (*AlbumMusic) Descriptor() ([]byte, []int) {
	return file_all_model_proto_rawDescGZIP(), []int{4}
}

func (x *AlbumMusic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AlbumMusic) GetTimeLength() int32 {
	if x != nil {
		return x.TimeLength
	}
	return 0
}

func (x *AlbumMusic) GetMusicId() int64 {
	if x != nil {
		return x.MusicId
	}
	return 0
}

func (x *AlbumMusic) GetAlbumId() int64 {
	if x != nil {
		return x.AlbumId
	}
	return 0
}

func (x *AlbumMusic) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

type File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" form:"id" query:"id"`
	Name      string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" form:"name" query:"name"`
	Format    FileType `protobuf:"varint,3,opt,name=format,proto3,enum=onij.FileType" json:"format,omitempty" form:"format" query:"format"`
	Size      int32    `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty" form:"size" query:"size"`
	ParentId  int64    `protobuf:"varint,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty" form:"parent_id" query:"parent_id"`
	Extra     string   `protobuf:"bytes,6,opt,name=extra,proto3" json:"extra,omitempty" form:"extra" query:"extra"`
	CreatedAt int64    `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" form:"created_at" query:"created_at"`
	UpdatedAt int64    `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" form:"updated_at" query:"updated_at"`
	Url       string   `protobuf:"bytes,10,opt,name=url,proto3" json:"url,omitempty" form:"url" query:"url"`
}

func (x *File) Reset() {
	*x = File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_model_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_all_model_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_all_model_proto_rawDescGZIP(), []int{5}
}

func (x *File) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *File) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *File) GetFormat() FileType {
	if x != nil {
		return x.Format
	}
	return FileType_FT_Unknown
}

func (x *File) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *File) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *File) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

func (x *File) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *File) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *File) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_all_model_proto protoreflect.FileDescriptor

var file_all_model_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x61, 0x6c, 0x6c, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x6f, 0x6e, 0x69, 0x6a, 0x1a, 0x09, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x0e, 0x61, 0x6c, 0x6c, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x95, 0x02, 0x0a, 0x05, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x26, 0x0a, 0x07, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x6f, 0x6e, 0x69, 0x6a, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x52,
	0x07, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x73, 0x75,
	0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x69, 0x73,
	0x73, 0x75, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x76, 0x5f, 0x75, 0x72,
	0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x76, 0x55, 0x72, 0x6c, 0x12, 0x20,
	0x0a, 0x0c, 0x6d, 0x70, 0x33, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x15,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x70, 0x33, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x72, 0x6c,
	0x12, 0x26, 0x0a, 0x0f, 0x6c, 0x79, 0x72, 0x69, 0x63, 0x73, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f,
	0x75, 0x72, 0x6c, 0x18, 0x16, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6c, 0x79, 0x72, 0x69, 0x63,
	0x73, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x21, 0x0a, 0x05, 0x61, 0x6c, 0x62, 0x75,
	0x6d, 0x18, 0x1e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6f, 0x6e, 0x69, 0x6a, 0x2e, 0x41,
	0x6c, 0x62, 0x75, 0x6d, 0x52, 0x05, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x12, 0x1d, 0x0a, 0x04, 0x74,
	0x61, 0x67, 0x73, 0x18, 0x1f, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x6f, 0x6e, 0x69, 0x6a,
	0x2e, 0x54, 0x61, 0x67, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x22, 0xc1, 0x02, 0x0a, 0x03, 0x54,
	0x61, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x49, 0x64, 0x12, 0x37, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x6f, 0x6e, 0x69,
	0x6a, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0c,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x25, 0x0a, 0x07,
	0x74, 0x61, 0x67, 0x5f, 0x62, 0x69, 0x7a, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e,
	0x6f, 0x6e, 0x69, 0x6a, 0x2e, 0x54, 0x61, 0x67, 0x42, 0x69, 0x7a, 0x52, 0x06, 0x74, 0x61, 0x67,
	0x42, 0x69, 0x7a, 0x12, 0x2b, 0x0a, 0x09, 0x74, 0x61, 0x67, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x6f, 0x6e, 0x69, 0x6a, 0x2e, 0x54, 0x61,
	0x67, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x08, 0x74, 0x61, 0x67, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x12, 0x28, 0x0a, 0x08, 0x74, 0x61, 0x67, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x6f, 0x6e, 0x69, 0x6a, 0x2e, 0x54, 0x61, 0x67, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x07, 0x74, 0x61, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x78, 0x74, 0x72,
	0x61, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x22, 0x89,
	0x01, 0x0a, 0x06, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a,
	0x0f, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x75, 0x72, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x46, 0x69,
	0x6c, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x33, 0x0a, 0x0c, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x6f, 0x6e,
	0x69, 0x6a, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x61,
	0x72, 0x74, 0x69, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x73, 0x22, 0xfd, 0x01, 0x0a, 0x05, 0x41,
	0x6c, 0x62, 0x75, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x12, 0x2e, 0x0a, 0x0a, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x6f, 0x6e, 0x69, 0x6a, 0x2e, 0x41, 0x6c,
	0x62, 0x75, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x26, 0x0a, 0x07, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x73, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6f, 0x6e, 0x69, 0x6a, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x73,
	0x74, 0x52, 0x07, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73,
	0x73, 0x75, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x69, 0x73, 0x73, 0x75, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x63, 0x6f, 0x76,
	0x65, 0x72, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x72, 0x6c, 0x12,
	0x19, 0x0a, 0x08, 0x6c, 0x69, 0x76, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6c, 0x69, 0x76, 0x65, 0x55, 0x72, 0x6c, 0x22, 0x9a, 0x01, 0x0a, 0x0a, 0x41,
	0x6c, 0x62, 0x75, 0x6d, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a,
	0x0b, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x19,
	0x0a, 0x08, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x6c, 0x62,
	0x75, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x61, 0x6c, 0x62,
	0x75, 0x6d, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x73, 0x5f, 0x61, 0x76, 0x61, 0x69, 0x6c,
	0x61, 0x62, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x41, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x22, 0xe9, 0x01, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x6f, 0x6e, 0x69, 0x6a, 0x2e, 0x46, 0x69, 0x6c, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x78,
	0x74, 0x72, 0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x72, 0x6c, 0x42, 0x10, 0x5a, 0x0e, 0x6f, 0x6e, 0x69, 0x6a, 0x2f, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_all_model_proto_rawDescOnce sync.Once
	file_all_model_proto_rawDescData = file_all_model_proto_rawDesc
)

func file_all_model_proto_rawDescGZIP() []byte {
	file_all_model_proto_rawDescOnce.Do(func() {
		file_all_model_proto_rawDescData = protoimpl.X.CompressGZIP(file_all_model_proto_rawDescData)
	})
	return file_all_model_proto_rawDescData
}

var file_all_model_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_all_model_proto_goTypes = []interface{}{
	(*Music)(nil),      // 0: onij.Music
	(*Tag)(nil),        // 1: onij.Tag
	(*Artist)(nil),     // 2: onij.Artist
	(*Album)(nil),      // 3: onij.Album
	(*AlbumMusic)(nil), // 4: onij.AlbumMusic
	(*File)(nil),       // 5: onij.File
	(ResourceType)(0),  // 6: onij.ResourceType
	(TagBiz)(0),        // 7: onij.TagBiz
	(TagGroup)(0),      // 8: onij.TagGroup
	(TagType)(0),       // 9: onij.TagType
	(ArtistType)(0),    // 10: onij.ArtistType
	(AlbumType)(0),     // 11: onij.AlbumType
	(FileType)(0),      // 12: onij.FileType
}
var file_all_model_proto_depIdxs = []int32{
	2,  // 0: onij.Music.artists:type_name -> onij.Artist
	3,  // 1: onij.Music.album:type_name -> onij.Album
	1,  // 2: onij.Music.tags:type_name -> onij.Tag
	6,  // 3: onij.Tag.resource_type:type_name -> onij.ResourceType
	7,  // 4: onij.Tag.tag_biz:type_name -> onij.TagBiz
	8,  // 5: onij.Tag.tag_group:type_name -> onij.TagGroup
	9,  // 6: onij.Tag.tag_type:type_name -> onij.TagType
	10, // 7: onij.Artist.artist_types:type_name -> onij.ArtistType
	11, // 8: onij.Album.album_type:type_name -> onij.AlbumType
	2,  // 9: onij.Album.artists:type_name -> onij.Artist
	12, // 10: onij.File.format:type_name -> onij.FileType
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_all_model_proto_init() }
func file_all_model_proto_init() {
	if File_all_model_proto != nil {
		return
	}
	file_api_proto_init()
	file_all_enum_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_all_model_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Music); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_all_model_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_all_model_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Artist); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_all_model_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Album); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_all_model_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlbumMusic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_all_model_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_all_model_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_all_model_proto_goTypes,
		DependencyIndexes: file_all_model_proto_depIdxs,
		MessageInfos:      file_all_model_proto_msgTypes,
	}.Build()
	File_all_model_proto = out.File
	file_all_model_proto_rawDesc = nil
	file_all_model_proto_goTypes = nil
	file_all_model_proto_depIdxs = nil
}
