// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package inject

import (
	"github.com/google/wire"
	"onij/handler"
	"onij/infra"
	"onij/infra/mysql"
	"onij/logic"
)

// Injectors from wire.go:

func InitializeApp() *App {
	db := mysql.NewMysqlCli()
	todDal := mysql.NewTodDal(db)
	tagDal := mysql.NewTagDal()
	relayDal := mysql.NewRelayDal(db)
	allInfra := &infra.AllInfra{
		TodDal:   todDal,
		TagDal:   tagDal,
		RelayDal: relayDal,
	}
	app := &App{
		AllInfra: allInfra,
	}
	return app
}

// wire.go:

var infraSet = wire.NewSet(mysql.NewMysqlCli, mysql.NewTagDal, mysql.NewTodDal, mysql.NewRelayDal, wire.Struct(new(infra.AllInfra), "*"))

var logicSet = wire.NewSet(logic.NewTodLogic, logic.NewRelayLogic, wire.Struct(new(logic.AllLogic), "*"))

var handlerSet = wire.NewSet(handler.NewRelayHandler, wire.Struct(new(handler.AllHandler), "*"))

var allSet = wire.NewSet(
	infraSet,
	logicSet,
	handlerSet, wire.Struct(new(App), "*"),
)

type App struct {
	*infra.AllInfra
}
