// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package inject

import (
	"github.com/google/wire"
	"onij/infra"
	"onij/infra/mysql"
	"onij/logic"
)

// Injectors from wire.go:

func InitDalForTest() *infra.AllInfra {
	db := mysql.NewMysqlCli()
	tagDal := mysql.NewTagDal(db)
	relayDal := mysql.NewRelayDal(db)
	fileDal := mysql.NewFileDal(db)
	musicDal := mysql.NewMusicDal(db)
	albumDal := mysql.NewAlbumDal(db)
	artistDal := mysql.NewArtistDal(db)
	allInfra := &infra.AllInfra{
		TagDal:    tagDal,
		RelayDal:  relayDal,
		FileDal:   fileDal,
		MusicDal:  musicDal,
		AlbumDal:  albumDal,
		ArtistDal: artistDal,
	}
	return allInfra
}

func InitializeApp() *App {
	db := mysql.NewMysqlCli()
	tagDal := mysql.NewTagDal(db)
	relayDal := mysql.NewRelayDal(db)
	fileDal := mysql.NewFileDal(db)
	musicDal := mysql.NewMusicDal(db)
	albumDal := mysql.NewAlbumDal(db)
	artistDal := mysql.NewArtistDal(db)
	allInfra := &infra.AllInfra{
		TagDal:    tagDal,
		RelayDal:  relayDal,
		FileDal:   fileDal,
		MusicDal:  musicDal,
		AlbumDal:  albumDal,
		ArtistDal: artistDal,
	}
	musicLogic := logic.NewMusicLogic(allInfra)
	fileLogic := logic.NewFileLogic(allInfra)
	albumLogic := logic.NewAlbumLogic(allInfra)
	artistLogic := logic.NewArtistLogic(allInfra)
	allLogic := &logic.AllLogic{
		MusicLogic:  musicLogic,
		FileLogic:   fileLogic,
		AlbumLogic:  albumLogic,
		ArtistLogic: artistLogic,
	}
	app := &App{
		AllInfra: allInfra,
		AllLogic: allLogic,
	}
	return app
}

// wire.go:

var infraSet = wire.NewSet(mysql.NewMysqlCli, mysql.NewTagDal, mysql.NewRelayDal, mysql.NewFileDal, mysql.NewMusicDal, mysql.NewAlbumDal, mysql.NewArtistDal, wire.Struct(new(infra.AllInfra), "*"))

var logicSet = wire.NewSet(logic.NewMusicLogic, logic.NewFileLogic, logic.NewAlbumLogic, logic.NewArtistLogic, wire.Struct(new(logic.AllLogic), "*"))

var allSet = wire.NewSet(
	infraSet,
	logicSet, wire.Struct(new(App), "*"),
)

type App struct {
	*infra.AllInfra
	*logic.AllLogic
}
